logging:
  level:
    root: INFO

spring:
  application:
    name: ^project.name^
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
springdoc:
  swagger-ui:
    try-it-out-enabled: false
    path: /api/v1/swagger
  api-docs:
    path: /api/v1/docs
